import { SERVER_DETAILS } from "../commons/constants";

export const MESS_ROUTINE_ACTIONS = {
  LOAD_MESS_ROUTINES: "MESS_ROUTINE_ACTIONS_LOAD_MESS_ROUTINES",
  SET_LOAD_MESS_ROUTINES_RESPONSE_STATUS:
    "MESS_ROUTINE_ACTIONS_SET_LOAD_MESS_ROUTINES_RESPONSE_STATUS",
  SET_MESS_ROUTINES: "MESS_ROUTINE_ACTIONS_SET_MESS_ROUTINES",
  ADD_MESS_ROUTINE: "MESS_ROUTINE_ACTIONS_ADD_MESS_ROUTINE",
  SET_ADD_MESS_ROUTINES_RESPONSE_STATUS:
    "ADD_MESS_ROUTINES_SET_ADD_MESS_ROUTINES_RESPONSE_STATUS",
  UPDATE_MESS_ROUTINES: "MESS_ROUTINE_ACTIONS_UPDATE_MESS_ROUTINES",
  SET_ERROR: "MESS_ROUTINE_ACTIONS_SET_ERROR",
};

export const MESS_ROUTINE_API = {
  ADD_MESS_ROUTINE: `${SERVER_DETAILS.API_URL}/mess/<<mess_id>>/routine`,
  GET_MESS_ROUTINES: `${SERVER_DETAILS.API_URL}/mess/<<mess_id>>/routine`,
};
