import { SERVER_DETAILS } from "../commons/constants";

export const INVENTORY_ACTIONS = {
  LOAD_ITEMS: "INVENTORY_ACTIONS_LOAD_ITEMS",
  SET_LOAD_ITEMS_RESPONSE_STATUS:
    "INVENTORY_ACTIONS_SET_LOAD_ITEMS_RESPONSE_STATUS",
  SET_ITEMS: "INVENTORY_ACTIONS_SET_ITEMS",
  ADD_ITEM: "INVENTORY_ACTIONS_ADD_ITEM",
  SET_ADD_ITEM_RESPONSE_STATUS:
    "INVENTORY_ACTIONS_SET_ADD_ITEM_RESPONSE_STATUS",
  UPDATE_ITEMS: "INVENTORY_ACTIONS_UPDATE_ITEMS",
  SET_ERROR: "INVENTORY_ACTIONS_SET_ERROR",
};

export const INVENTORY_API = {
  ADD_ITEM: `${SERVER_DETAILS.API_URL}/mess/<<mess_id>>/inventory`,
  GET_ITEMS: `${SERVER_DETAILS.API_URL}/mess/<<mess_id>>/inventory`,
};
