import { SERVER_DETAILS } from "../commons/constants";

export const AUTH_ACTIONS = {
  LOGIN: "AUTH_ACTIONS_LOGIN",
  SIGNUP: "AUTH_ACTIONS_SIGNUP",
  LOGOUT: "AUTH_ACTIONS_LOGOUT",
  SET_LOGIN_RESPONSE_STATUS: "AUTH_ACTIONS_SET_LOGIN_RESPONSE_STATUS",
  SET_SIGNUP_RESPONSE_STATUS: "AUTH_ACTIONS_SET_SIGNUP_RESPONSE_STATUS",
  SET_ERROR: "AUTH_ACTIONS_SET_ERROR",
  SET_LOGIN_STATUS: "AUTH_ACTIONS_SET_LOGIN_STATUS",
  LOAD_USER_INFO: "AUTH_ACTIONS_LOAD_USER_INFO",
  SET_LOGGED_IN_USER_INFO: "AUTH_ACTIONS_SET_LOGGED_IN_USER_INFO",
  SET_LOAD_USER_INFO_RESPONSE_STATUS:
    "AUTH_ACTIONS_SET_LOAD_USER_INFO_RESPONSE_STATUS",
};

export const AUTH_API = {
  LOGIN: `${SERVER_DETAILS.API_URL}/users/login`,
  SIGNUP: `${SERVER_DETAILS.API_URL}/users/signup`,
  LOAD_USER_INFO: `${SERVER_DETAILS.API_URL}/users/me`,
};

export const LOGIN_STATUS = {
  UNKNOWN: "LOGIN_STATUS_UNKNOWN",
  LOGGED_IN: "LOGIN_STATUS_LOGGED_IN",
  LOGGED_OUT: "LOGIN_STATUS_LOGGED_OUT",
};
