export const RESPONSE_STATUS = {
  SUCCESS: "RESPONSE_STATUS_SUCCESS",
  FAILED: "RESPONSE_STATUS_FAILED",
  PENDING: "RESPONSE_STATUS_PENDING",
  NONE: "RESPONSE_STATUS_NONE",
};

export const SERVER_DETAILS = {
  // TODO: CHANGE LATER
  URL: "http://127.0.0.1:3000",
  API_URL: "http://127.0.0.1:3000/api/v1",
};
