import { SERVER_DETAILS } from "../commons/constants";

export const STUDENT_ACTIONS = {
  LOAD_STUDENTS: "STUDENT_ACTIONS_LOAD_STUDENTS",
  SET_LOAD_STUDENTS_RESPONSE_STATUS:
    "STUDENT_ACTIONS_SET_LOAD_STUDENTS_RESPONSE_STATUS",
  SET_STUDENTS: "STUDENT_ACTIONS_SET_STUDENTS",
  ADD_STUDENT: "STUDENT_ACTIONS_ADD_STUDENT",
  SET_ADD_STUDENT_RESPONSE_STATUS:
    "STUDENT_ACTIONS_SET_ADD_STUDENT_RESPONSE_STATUS",
  UPDATE_STUDENTS: "STUDENT_ACTIONS_UPDATE_STUDENTS",
  ASSIGN_ROLE: "STUDENT_ACTIONS_ASSIGN_ROLE",
  SET_ASSIGN_ROLE_RESPONSE_STATUS:
    "STUDENT_ACTIONS_SET_ASSIGN_ROLE_RESPONSE_STATUS",
  UPDATE_ROLE: "STUDENT_ACTIONS_UPDATE_ROLE",
  SET_ERROR: "STUDENT_ACTIONS_SET_ERROR",
};

export const STUDENT_API = {
  ADD_STUDENT: `${SERVER_DETAILS.API_URL}/mess/<<mess_id>>/student`,
  GET_STUDENTS: `${SERVER_DETAILS.API_URL}/mess/<<mess_id>>/student`,
  ASSIGN_ROLE: `${SERVER_DETAILS.API_URL}/mess/<<mess_id>>/student/roles`,
};
